blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/soil-kt/soil/discussions/categories/ideas
    about: Suggest an idea for this project.
  - name: Ask a question
    url: https://github.com/soil-kt/soil/discussions
    about: Questions on soil usage
