name: Check PR

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "art/**"
      - "*.md"

concurrency:
  group: pull_request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotless:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Apply spotless rules
        run: ./gradlew spotlessApply

      - name: Commit newly formatted files
        uses: stefanzweifel/git-auto-commit-action@b863ae1933cb653a53c021fe36dbb774e1fb9403 # v5.2.0
        with:
          file_pattern: "**/*.kt **/*.gradle.kts **/*.yml"

  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        job: [ test ]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Copy CI gradle.properties
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1

      # macos-latest
      - name: Run tests on macos
        if: matrix.os == 'macos-latest' && matrix.job == 'test'
        run: ./gradlew iosX64Test

      # ubuntu-latest
      - name: Run tests on linux
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
        run: |
          ./gradlew testDebugUnitTest desktopTest wasmJsTest
