name: Check PR

on:
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - "docs/**"

concurrency:
  group: pull_request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotless:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Java
      uses: actions/setup-java@v4
      with:
        distribution: zulu
        java-version: 17

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        cache-read-only: ${{ github.ref != 'refs/heads/main' }}

    - name: Apply Spotless rules
      run: ./gradlew spotlessApply

    - name: Commit newly formatted files
      uses: stefanzweifel/git-auto-commit-action@v5
      with:
        file_pattern: "**/*.kt **/*.gradle.kts **/*.yml"
