name: Check PR

on:
  pull_request:
    branches: ["main"]
    paths-ignore:
      - "docs/**"
      - "art/**"
      - "*.md"

concurrency:
  group: pull_request-${{ github.ref }}
  cancel-in-progress: true

jobs:
  spotless:
    runs-on: ubuntu-latest
    timeout-minutes: 60

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Check spotless rules
        run: ./gradlew spotlessCheck

  build:
    strategy:
      matrix:
        os: [ macos-latest, ubuntu-latest ]
        job: [ test ]

    runs-on: ${{ matrix.os }}
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Copy CI gradle.properties
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: Setup java
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup gradle
        uses: gradle/actions/setup-gradle@ac638b010cf58a27ee6c972d7336334ccaf61c96 # v4.4.1

      # macos-latest
      - name: Run tests on macos
        if: matrix.os == 'macos-latest' && matrix.job == 'test'
        run: ./gradlew iosX64Test

      # ubuntu-latest
      - name: Run tests on linux
        if: matrix.os == 'ubuntu-latest' && matrix.job == 'test'
        run: |
          ./gradlew testDebugUnitTest desktopTest wasmJsTest
