name: Publish
on:
  workflow_dispatch:
    inputs:
      deploy_api_reference:
        description: 'Deploy API Reference?'
        required: true
        default: true
        type: boolean

jobs:
  publish:
    runs-on: macos-latest

    permissions:
      contents: write

    env:
      RELEASE_PAGES_BRANCH: main

    steps:
      - name: Check branch
        if: ${{ !contains(github.ref, 'refs/heads/release/') }}
        run: |
          echo "This action runs only on branches that start with 'release/'"
          exit 1

      - name: Checkout sources
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          fetch-depth: 0

      - name: Create Release Tag
        run: |
            export VERSION=$(cat gradle.properties | grep "version" | awk -F '=' '{print $2}') && \
            gh config set prompt disabled && \
            gh release create \
              --target "$GITHUB_REF_NAME" \
              --title "$VERSION" \
              --generate-notes \
              $VERSION
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup JDK
        uses: actions/setup-java@3a4f6e1af504cf6a31855fa899c6aa5355ba6c12 # v4.7.0
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@d9c87d481d55275bb5441eef3fe0e46805f9ef70 # v3.5.0

      - name: Publish to Maven Central
        run: ./gradlew publishAndReleaseToMavenCentral --no-configuration-cache
        env:
          ORG_GRADLE_PROJECT_mavenCentralUsername: ${{ secrets.MAVEN_CENTRAL_USERNAME }}
          ORG_GRADLE_PROJECT_mavenCentralPassword: ${{ secrets.MAVEN_CENTRAL_PASSWORD }}
          ORG_GRADLE_PROJECT_signingInMemoryKey: ${{ secrets.GPG_KEY }}
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword: ${{ secrets.GPG_KEY_PASSWORD }}

      - name: Build API Reference
        if: ${{ github.event.inputs.deploy_api_reference == 'true' }}
        run: ./gradlew dokkaHtmlMultiModule

      - name: Deploy API Reference to Cloudflare Pages
        if: ${{ github.event.inputs.deploy_api_reference == 'true' }}
        uses: cloudflare/wrangler-action@da0e0dfe58b7a431659754fdf3f186c529afbe65 # v3.14.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_PAGES_DEPLOY_API_TOKEN }}
          command: pages deploy build/dokka/htmlMultiModule --project-name=soil-api-reference --branch ${{ env.RELEASE_PAGES_BRANCH }}
