name: Run Unit Tests

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module name to test (e.g., soil-query-compose-runtime)'
        required: true
        type: string
      tests:
        description: 'Test class to run (optional, e.g., soil.query.compose.runtime.AwaitTest)'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@017a9effdb900e5b5b2fddfb590a105619dca3c3 # v4.4.2

      - name: Run unit tests
        run: |
          if [ -n "${{ github.event.inputs.tests }}" ]; then
            ./gradlew :${{ github.event.inputs.module }}:testDebugUnitTest --tests "${{ github.event.inputs.tests }}"
          else
            ./gradlew :${{ github.event.inputs.module }}:testDebugUnitTest
          fi
