name: Run Unit Tests

on:
  workflow_dispatch:
    inputs:
      module:
        description: 'Module name to test (e.g., soil-query-compose-runtime)'
        required: true
        type: string
      tests:
        description: 'Test class to run (optional, e.g., soil.query.compose.runtime.AwaitTest)'
        required: false
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Setup JDK
        uses: actions/setup-java@c5195efecf7bdfc987ee8bae7a71cb8b11521c00 # v4.7.1
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@06832c7b30a0129d7fb559bcc6e43d26f6374244 # v4.3.1

      - name: Run unit tests
        run: |
          if [ -n "${{ github.event.inputs.tests }}" ]; then
            ./gradlew :${{ github.event.inputs.module }}:testDebugUnitTest --tests "${{ github.event.inputs.tests }}"
          else
            ./gradlew :${{ github.event.inputs.module }}:testDebugUnitTest
          fi
